name: my_finance_app
description: Personal finance management app with Clean Architecture.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Internationalisation
  intl: ^0.19.0

  # Utils
  equatable: ^2.0.5
  dartz: ^0.10.1
  uuid: ^4.4.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3
  custom_lint: ^0.7.6
  riverpod_lint: ^2.4.3

flutter:
  uses-material-design: true
